# permissions for end users to edit approvals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: approval-k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: approval-editor-role
rules:
- apiGroups:
  - approval.acp.ag.ch
  resources:
  - approvals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - approval.acp.ag.ch
  resources:
  - approvals/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch